<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Swing Music</AssemblyName>
    <RootNamespace>SwingMusic</RootNamespace>
    <ApplicationIcon>assets\swingmusiclogo.ico</ApplicationIcon>
    <Version>2.0.0</Version>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3124.44" />
  </ItemGroup>

  <ItemGroup>
    <None Include="assets\swingmusiclogo.ico" />
    <EmbeddedResource Include="assets\swingmusiclogo.png" />
  </ItemGroup>
</Project>
